### ISSUE TITLE
!new does not work anymore as of today

### ISSUE THREAD

**Issue by Timotej32** [eartharoid/DiscordTickets#1]
Hello, 

I've been using the bot for a while and had no issues, until yesterday when opening tickets stopped working. I've tried with "fresh install" on different PCs on different discord servers and I get the same error, if you have any idea what could the reason be.

[INFO | 5:11:09] disc#123456 used the 'new' command
[WARN | 5:11:09] An error was not caught
[ERROR | 5:11:09] Uncaught error:
DiscordAPIError: Invalid Form Body
type: Value "text" is not int.
    at item.request.gen.end (E:\Tick\Tickets\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:85:15)
    at then (E:\Tick\Tickets\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Best regards

**Comment by Timotej32** [comment]
I fixed it by changing this line in new.js:
message.guild.createChannel(`ticket-${id}`).then(async c => {  

To

message.guild.createChannel(`ticket-${id}`, 'text').then(async c => {

**Comment by eartharoid** [comment]
Fixed issue with update.
