### ISSUE TITLE
when ever i close the repl.it tap, the bot stops working

### ISSUE THREAD

**Issue by krussedull** [eartharoid/DiscordTickets#118]
when ever i close the repl.it tap, the bot stops working

**Comment by eartharoid** [comment]
This isn't an issue with the bot. REPL.it is not recommended for hosting as it is not designed for this purpose, but here's a generic tutorial for it: https://repl.it/talk/learn/Hosting-discordjs-bots-on-replit-Works-for-both-discordjs-and-Eris/11027
