### ISSUE TITLE
dont know how to run bot?

### ISSUE THREAD

**Issue by SunRise-ppl** [eartharoid/DiscordTickets#13]
i have no clue how to run the bot

**Comment by eartharoid** [comment]
To be fair the instructions on the wiki aren't the best.
The [Getting Started](https://github.com/eartharoid/DiscordTickets/wiki/2.-Getting-Started) wiki page explains how to install the requirements and create the bot user.
Rename `example-config.json` to `config.json` and edit the file, adding your bot token, guild/server ID, and the other IDs for channels and categories etc.

Then add the bot to your server here: https://discordapp.com/oauth2/authorize?client_id=INSTERT_BOT_ID_HERE&scope=bot, using your own bot ID in the URL.

You should then be able to type `node .` and the bot will start, although you should look into using PM2 or Linux screens to keep it running constantly.
