### ISSUE TITLE
The bot won't start.

### ISSUE THREAD

**Issue by BellCocoa** [eartharoid/DiscordTickets#15]
They say there is no module leeks.js...
What should I do?

**Comment by eartharoid** [comment]
Run `npm i` to install the dependancies.
just to make sure you don't get version issues, run `npm i discord.js@11.6.4` afterwards.

**Comment by BellCocoa** [comment]
It boots up, but I get an error when I type a command...
https://pastebin.com/Z1uAWnwz

**Comment by eartharoid** [comment]
Make sure you have fully configured the bot (config.json) and that the cannel category exists/the bot has perms.

**Comment by BellCocoa** [comment]
I understand. Thank you.
Another ticket channel created by your question is
Can't you get a lock on it?

**Comment by eartharoid** [comment]
> Can't you get a lock on it?
?
