### ISSUE TITLE
ok the bot is good i manged to turn it on and it works. Except for one thing.

### ISSUE THREAD

**Issue by JoshuaKim2203** [eartharoid/DiscordTickets#16]
the `!new <text>` command every time i do `!new something bla bla bla` it would say i have to add text to it. i did this multiple times and it wont work.

**Comment by eartharoid** [comment]
Could you send a screenshot?

**Comment by JoshuaKim2203** [comment]
yea
here watch this short youtube clip
and btw you can contact my discord so we can chat instead of leaving comments. `Typerious#1482`

https://youtu.be/2BWt2EDsGGw

**Comment by JoshuaKim2203** [comment]
IT works now. It was something to do with roles. so i gave it the right roles and it now works.

**Comment by JoshuaKim2203** [comment]
wait not yet. like when i do `!new something` it only creates a ticket channel but no messages. it dosent dm staff or leave messages or anything. And it says to add support team role and it dosent work. i put the support team id into it  but it wont work. help

**Comment by eartharoid** [comment]
> the` !new <text>` command every time i do `!new something bla bla bla` it would say i have to add text to it. 

The 'new ticket' command requires a brief description.

> it only creates a ticket channel but no messages. it dosent dm staff or leave messages or anything.

There should be an error in console. Without seeing it I'm going to assume the bot still doesn't have the right permissions. Giving it `ADMINISTRATOR` permission should fix it (but if you'd rather not, the bot needs to be able to read and send messages, embed links, and upload attachments in any channel you want commands to work in, and in the ticket category).

**Comment by JoshuaKim2203** [comment]
I gave it all perms possible
but it says it dosent have a support team role.

**Comment by eartharoid** [comment]
Can you send your config (remove the token).

**Comment by JoshuaKim2203** [comment]
https://repl.it/@JoshuaKim2203/DiscordTickets#config.json
i used repl.it
there

**Comment by eartharoid** [comment]
`"supportRole": "@Support Team",`
this needs to be the ID of the role.
Type `\@Support Team`  on your Discord server and send the message, you'll get something like `<@&0123456789>` - just copy the number, not the <@&>.

**Comment by JoshuaKim2203** [comment]
oh i used the id before but didnt work. ok lemme do the way you said

**Comment by JoshuaKim2203** [comment]
it works! thanks!
