### ISSUE TITLE
message is not defined

### ISSUE THREAD

**Issue by Advewave** [eartharoid/DiscordTickets#18]
**Describe the bug**
i am having this error: https://hastebin.com/omayajeloz.shell

**To Reproduce**
just run the bot

**Additional context**
i have done `npm i discord.js@11.6.4` as stated in #12

**Comment by eartharoid** [comment]
It looks like you tried to update the bot to work with `discord.js@12.x`.
Line 105 should be:
```js
client.channels.get(config.logChannel).send(embed)
```
but your line 105 is:
```js
message.guild.channels.cache.get(config.logChannel).send(embed);
```
Which looks (almost) correct for `discord.js@12.x` but you said you specifically installed v11.6.4.

The current problem is that you've changed it too much. `channels.cache.get` is fine for v12 but you replaced `client` with `message.guild`. `message` does not exist as this is before a message has been sent, when the bot it starting up.

If you want it to just work, undo your v12 update changes. If you need it to work with v12 then change line 105 to
```js
client.channels.cache.get(config.logChannel).send(embed);
```

**Comment by eartharoid** [comment]
The bot now supports discord.js v12.
