### ISSUE TITLE
New Ticket

### ISSUE THREAD

**Issue by changawer13** [eartharoid/DiscordTickets#2]
**Open New Ticket**
I try to create a new ticket and I get an error thinking that I already have one open, where is none.

**To Reproduce**
1. Go to 'channel'
2. Type  '!new test (or anything)'
3. See error 'You already have an open ticket.'

**Screenshots**
https://i.imgur.com/AyXJ5UB.png

**Comment by eartharoid** [comment]
Oo I should probably check this more often.

The bot takes the first 4 digits of your user id and your 4 digit discriminator to create a ticket channel name that is (hopefully) unique to you (prevents the need for a file or database to store ticket channels), and then uses that 8 digit code to check if you have a channel already.

This is currently working fine on my test server, so if you still have the problem _(hopefully you managed to fix it already)_, double-check there are no ticket channels.

It is possible (but unlikely) that 2 members of a server have the same 4 numbers at the start of their id and the same discriminator, which would produce the same ticket channel name.

**Comment by iDrunK65** [comment]
i have the solution i make a pull request
