### ISSUE TITLE
?

### ISSUE THREAD

**Issue by user3u3u** [eartharoid/DiscordTickets#20]
https://imgur.com/SWbw6gH

**Comment by user3u3u** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/69444274/89784734-b3bdc080-db08-11ea-8fea-b387552fb910.png)

**Comment by eartharoid** [comment]
Make sure you have discord.js v11 not v12: `npm i discord.js@11.6.4`

I'll update the code to v12 soon.
