### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by RobTech1** [eartharoid/DiscordTickets#24]
When i start the bot i get this error https://pastebin.com/wqzxBAQG

**Comment by eartharoid** [comment]
Have you added the bot to your server?

**Comment by RobTech1** [comment]
Yes

**Comment by eartharoid** [comment]
You need discord.js v12.
Run `npm i`

**Comment by RobTech1** [comment]
I have done that

**Comment by RobTech1** [comment]
I can try reinstalling it

**Comment by RobTech1** [comment]
Now when i start it it says https://pastebin.com/nhNj78WW

**Comment by eartharoid** [comment]
Either you haven't set `guild` in your config, or the ID is incorrect. Make sure yoou set the other IDs too (support role and category ID)

**Comment by RobTech1** [comment]
Ok

**Comment by RobTech1** [comment]
Now it works thanks
