### ISSUE TITLE
Export error when launching the bot.

### ISSUE THREAD

**Issue by ThatGuyJacobee** [eartharoid/DiscordTickets#31]
**Describe the bug**
I can't seem to be able to start the bot, as I keep getting this one export error from a module. I've attached the error message below. I've tried fresh installing but I still seem to be getting this issue.

**To Reproduce**
Steps to reproduce the behaviour:
- Start the bot, it errors and crashes.

**Expected behavior**
- The bot starts and everything works.

**Screenshots**
![image](https://user-images.githubusercontent.com/42719082/92325033-3883f780-f03f-11ea-9e2e-7ec3acb6547b.png)
![image](https://user-images.githubusercontent.com/42719082/92325056-6c5f1d00-f03f-11ea-80f2-c752e8fd6bbf.png)
[2020-09-06T11_48_53_312Z-debug.log](https://github.com/eartharoid/DiscordTickets/files/5179580/2020-09-06T11_48_53_312Z-debug.log)

**Comment by eartharoid** [comment]
Update Node.JS to v13 or higher

**Comment by ThatGuyJacobee** [comment]
I've got it at v13.3.0 already 😞
![image](https://user-images.githubusercontent.com/42719082/92331281-7c8df100-f06d-11ea-86b5-dcef1d6d84d7.png)

**Comment by eartharoid** [comment]
Oh.....
You could try Node v14 or a different version Sequelize maybe. I don't really know why.

**Comment by ThatGuyJacobee** [comment]
Alright, I'll first try node v.14 and after sequelize 👌
Thanks for the extremely fast replies haha.

**Comment by ThatGuyJacobee** [comment]
Awesome, it seems to be working on Node v.14!
Thanks alot @eartharoid and thank you for making this project open source. ❤️
