### ISSUE TITLE
Add a ticket transcript option.

### ISSUE THREAD

**Issue by lebon1377** [eartharoid/DiscordTickets#4]
You should add a ticket transcript option so we can view the message history.

**Comment by eartharoid** [comment]
How would this work?
Would it give you a text file to download? Or maybe give you a link to a page?

**Comment by lebon1377** [comment]
We would prefer a text file and of you want a pastebin or hastebin option too.

**Comment by eartharoid** [comment]
Ok. I might add this when I eventually update this.

**Comment by wolfier74** [comment]
> We would prefer a text file and of you want a pastebin or hastebin option too.

Hastebin and pastebin is good idea, I suggested it here: https://github.com/eartharoid/DiscordTickets/issues/106
