### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by WoollenPanda275** [eartharoid/DiscordTickets#45]
`[23:27:21 | ERROR] TypeError: Cannot read property 'length' of undefined
    at Object.execute (C:\Users\*****\OneDrive\Desktop\Discord Bots\Ryans server\src\commands\help.js:34:14)
    at Object.execute (C:\Users\*****\OneDrive\Desktop\Discord Bots\Ryans server\src\events\message.js:102:12)
`

**Comment by WoollenPanda275** [comment]
Thats all it gives me

**Comment by eartharoid** [comment]
Have you modified the bot at all?

**Comment by WoollenPanda275** [comment]
apart from adding what im supposed to no

**Comment by WoollenPanda275** [comment]
should i delete it and redownload

**Comment by eartharoid** [comment]
*(Unless I missed one,)* all of the command files have a description, so unless you've got an extra file in your commands directory, I don't know why.

Yes, try downloading it again.

**Comment by WoollenPanda275** [comment]
Its working now :)
