### ISSUE TITLE
What is meant by db and archive token

### ISSUE THREAD

**Issue by koushikpuppala5** [eartharoid/DiscordTickets#67]
Can you please explain.env file and what are those in that file

**Comment by koushikpuppala5** [comment]
👎

**Comment by eartharoid** [comment]
The `DB_` settings are for the database. If you are using the default database which is SQLite, you can ignore all of them as they are only required for connecting to a database server like MySQL. The `ARCHIVES_KEY` is basically a password that will be used if you want to use the web archives/transcripts with the [DiscordTickets-Portal](https://github.com/eartharoid/DiscordTickets-Portal). The key needs to be the same in the ENV file for both.

**Comment by eartharoid** [comment]
Join [my Discord server](https://go.eartharoid.me/discord) if you have any more questions.
