### ISSUE TITLE
List Users Involved in Ticket

### ISSUE THREAD

**Issue by ScottUK** [eartharoid/DiscordTickets#69]
**Describe the solution you'd like**
A list of users that have sent a message after the ticket has been closed in the logs. A lot of @ s of the users would be nice for us to look at our moderator's statistics on tickets.

**Additional context**
![image](https://user-images.githubusercontent.com/24849194/99615012-986d2600-2a12-11eb-90a5-30269d245106.png)
Possibly something similar to the above.

**Comment by eartharoid** [comment]
Possibly. I think the easiest way to do this would be to use the archives JSON files, but then this wouldn't be possible if you had web archives disabled.

**Comment by eartharoid** [comment]
Added in [7b0e2d8](https://github.com/eartharoid/DiscordTickets/commit/7b0e2d8fed1b80df86501dffb043a8cf40c57e00):

![](https://i.imgur.com/i9mxXsj.png)

It only works if you have web archives enabled as it uses the entities JSON file, which only includes users who have participated, so you won't see bots unless a member mentioned/interacted with one.
