### ISSUE TITLE
(prefix)closeall

### ISSUE THREAD

**Issue by DIBSTERYT** [eartharoid/DiscordTickets#85]
**Is your feature request related to a problem? Please describe.**
Nope.
**Describe the solution you'd like**
This command would close every single ticket that is currently open. Another command that could go with this would be (prefix)deleteall. This would delete every single ticket.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by OliverCordingl1** [comment]
Having a go at the closeall command currently, I'll be done soon and put in a pull request.

**Comment by OliverCordingl1** [comment]
(As with the deleteall command, I'm assuming this should be easy enough as well)

**Comment by OliverCordingl1** [comment]
Thinking about it, delete all might be a bit dangerous with the current permission foundations the projects have. I won't work on it unless anybody says they 100% want it to happen. In the meantime, closeall command is nearly done. It is just a tinkered version of `close.js`.

I currently have got it bare - there aren't any arguments or anything. I am thinking about later adding an argument where all older than a certain amount of days can be closed. Any ideas on how that would look in terms of the usage?

**Comment by eartharoid** [comment]
Like `closeall 2w` or `closeall 1mo`?

Ideally, it would be since last the last message, not since it was created, but I think doing it based on the creation date in the database would be significantly easier.

**Comment by OliverCordingl1** [comment]
> Like `closeall 2w` or `closeall 1mo`?
> 
> Ideally, it would be since last the last message, not since it was created, but I think doing it based on the creation date in the database would be significantly easier.

I can possibly do an option to base off of creation date / last message? Could also be a setting in config.js.
If I have time I'll work on doing it by last message, but I'll prioritise doing it off of creationdate / lastmodified.
