### ISSUE TITLE
Cannot use any commands

### ISSUE THREAD

**Issue by VogueMist** [eartharoid/DiscordTickets#86]
Might be my setup tbh but I get this when using one of the commands. Thanks in advance! 

![image](https://user-images.githubusercontent.com/48735695/104605917-03378800-5677-11eb-89eb-b3e279ced6de.png)

**Comment by eartharoid** [comment]
You need to update Node.JS.

**Comment by VogueMist** [comment]
> You need to update Node.JS.

Thanks for the quick response

**Comment by VogueMist** [comment]
@eartharoid you know lowest version I can use? Most recent don't support my old win7 laptop

**Comment by eartharoid** [comment]
Node.js >12 is required to fix this problem. I can't remember if the bot uses any features from v13+.
