### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by wolfier74** [eartharoid/DiscordTickets#99]
Hello, can you add option to use mongodb for storing data?

**Comment by eartharoid** [comment]
Unfortunately not, as Sequelize doesn't support it. :(

**Comment by wolfier74** [comment]
:/ Why you are using sequelize? You can use mongose for making mongodb support

**Comment by eartharoid** [comment]
Sequelize allows the bot to support Postgres, MySQL, MariaDB, SQLite and Microsoft SQL Server with very little code. Adding MongoDB support would add a lot of complexity as everything that uses the database will need to have code for both Sequelize and Mongoose.

**Comment by wolfier74** [comment]
Thats sad that you will not add it. Sometimes sqlite on replit is wiped (not all data are there, some data can disappear)
